## Generate and load data

In [11]:
import sys; sys.path.append(2*'../')

from rl4co.data.generate_data import generate_dataset

In [12]:
??generate_dataset

Signature:
generate_dataset(
    filename=None,
    data_dir='data',
    name=None,
    problem='all',
    data_distribution='all',
    dataset_size=10000,
    graph_sizes=[20, 50, 100],
    overwrite=False,
    seed=1234,
    disable_warning=True,
)
Source:   
def generate_dataset(
    filename=None,
    data_dir="data",
    name=None,
    problem="all",
    data_distribution="all",
    dataset_size=10000,
    graph_sizes=[20, 50, 100],
    overwrite=False,
    seed=1234,
    disable_warning=True,
):
    """We keep a similar structure as in Kool et al. 2019 but save and load the data as npz
    This is way faster and more memory efficient than pickle and also allows for easy transfer to TensorDict
    """
    assert filename is None or (
        len(problem) == 1 and len(graph_sizes) == 1
    ), "Can only specify filename when generating a single dataset"

    distributions_per_problem = {
        "tsp": [None],
        "vrp": [None],
        "pctsp": [None],
        "op": ["const", "

In [3]:
generate_dataset(problem='vrp', dataset_size=10_000, graph_sizes=[100], seed=1234, name='test')

## Load data with Numpy

In [4]:
# You may simply load with NumPy directly. Npz files are way more efficient than pickle files.
# The generated data uses the same process as Kool et al. (2019) and i

import numpy as np


fname = 'data/vrp/vrp100_test_seed1234.npz'
data = np.load(fname)

print(data.files)

print(data['locs'].shape)
print(data['demand'])

['depot', 'locs', 'demand', 'capacity']
(10000, 100, 2)
[[1. 3. 1. ... 7. 9. 5.]
 [6. 2. 5. ... 9. 8. 2.]
 [6. 2. 6. ... 1. 4. 1.]
 ...
 [4. 9. 7. ... 3. 7. 2.]
 [4. 5. 9. ... 8. 6. 6.]
 [5. 1. 9. ... 9. 5. 6.]]


In [5]:
# We can also load the data directly into a TensorDict with `load_data` method

from rl4co.envs import CVRPEnv

td = CVRPEnv.load_data(fname)

print(td['demand'])

tensor([[0.0200, 0.0600, 0.0200,  ..., 0.1400, 0.1800, 0.1000],
        [0.1200, 0.0400, 0.1000,  ..., 0.1800, 0.1600, 0.0400],
        [0.1200, 0.0400, 0.1200,  ..., 0.0200, 0.0800, 0.0200],
        ...,
        [0.0800, 0.1800, 0.1400,  ..., 0.0600, 0.1400, 0.0400],
        [0.0800, 0.1000, 0.1800,  ..., 0.1600, 0.1200, 0.1200],
        [0.1000, 0.0200, 0.1800,  ..., 0.1800, 0.1000, 0.1200]])


/home/cbhua/miniconda3/envs/rl4co_new/lib/python3.10/site-packages/torchrl/__init__.py:26: UserWarning: failed to set start method to spawn, and current start method for mp is fork.
  warn(
/home/cbhua/miniconda3/envs/rl4co_new/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


> NOTE: only in CVRP, the demand is first scaled, hence the difference in numbers

## Generate main table data


In [6]:
num_instances = 10_000
graph_sizes = [20, 50]
problems = ['tsp', 'vrp']


for problem in problems:
    generate_dataset(problem=problem, name='test', 
                     dataset_size=num_instances, graph_sizes=graph_sizes, seed=1234 )

## Generate generalization data

In [14]:
num_instances = 1000
graph_sizes = [10, 20, 50, 75, 100, 125, 150, 200, 500, 1000]
problems = ['tsp', 'vrp']


for problem in problems:
    generate_dataset(problem=problem, name='generalization', 
                     dataset_size=num_instances, graph_sizes=graph_sizes, seed=1234 )

?
?


In [8]:
# # Large scale: less instances, more graph sizes
# num_instances = 100
# graph_sizes = [500, 1000]
# problems = ['tsp', 'vrp']


# for problem in problems:
#     generate_dataset(problem=problem, name='test_generalization', 
#                      dataset_size=num_instances, graph_sizes=graph_sizes, seed=1234 )